export const CLIENT_ID = "VHFMRVPNPVEVZ1K0EPR0F4NQITW0FDEMPFR3KSFZJQ5YGKUL";
export const CLIENT_SECRET = "HW33JHSL5QPRNKKQWSEX12PHV4QPZ1V1BQYFLH5TISXIGIY2";
export const API_URL = "https://api.foursquare.com/v2/venues/explore";
